### ISSUE TITLE
Bipolar hall sensor

### ISSUE THREAD

**Issue by stefaandesmet2003** [francescovannini/espmeter#1]
Hi, congratulations with this interesting project. I tried something similar a while ago, the gas meter looks almost identical too.
But I couldn't get the detection of the rotating magnet to work with a bipolar hall sensor like yours. I had ss41f, a cheap sensor from ebay. The output would turn on when the magnet passes, but never turn off, because of the negative Brp magnetic field required. How did you solve this?
I also tried unipolar oh137, but it's not sensitive enough to be triggered by the magnet.

**Comment by francescovannini** [comment]
Hi! Thanks for you feedback. I guess I don't have this problem due to the fact that the sensor stays on only for a short amount of time, just enough to detect the magnet; then power is cut and I presume this is what resets the sensor.
